In [12]:
import pandas as pd
path="/Users/apoorva/Desktop/untitled folder 4/train_dataset.csv"
data=pd.read_csv(path)
print(data)
print(data.info())

       Serial No  Solidity  Eccentricity  EquivDiameter  Extrema  FilledArea  \
0          13126     10.30          22.5          2.000     6.95      0.0726   
1          12936      7.41          20.3          1.010    20.60      0.0207   
2          28006     12.60          19.5          3.810     9.84      0.2990   
3          24884      5.81          21.9          3.090     4.79      0.1940   
4          10680      7.51          17.3          0.751    15.40      0.0110   
...          ...       ...           ...            ...      ...         ...   
21363      18507     14.10          22.2          3.320    18.40      0.2120   
21364      15177     12.10          18.0          1.820    20.30      0.0702   
21365       4328      5.72          22.2          4.750     3.81      0.3980   
21366      28310      8.33          17.5          3.230     5.74      0.3010   
21367      15294     11.80          11.1          1.170    21.50      0.0262   

       Extent  Orientation  EulerNumber

In [2]:
inputs=data.drop(['Serial No','microorganisms'],axis=1)
print("inputs",inputs)
outputs=data['microorganisms']
print(outputs)

inputs        Solidity  Eccentricity  EquivDiameter  Extrema  FilledArea  Extent  \
0         10.30          22.5          2.000     6.95      0.0726    5.00   
1          7.41          20.3          1.010    20.60      0.0207    4.57   
2         12.60          19.5          3.810     9.84      0.2990    6.67   
3          5.81          21.9          3.090     4.79      0.1940    3.34   
4          7.51          17.3          0.751    15.40      0.0110    5.36   
...         ...           ...            ...      ...         ...     ...   
21363     14.10          22.2          3.320    18.40      0.2120    6.00   
21364     12.10          18.0          1.820    20.30      0.0702    7.43   
21365      5.72          22.2          4.750     3.81      0.3980    2.27   
21366      8.33          17.5          3.230     5.74      0.3010    6.80   
21367     11.80          11.1          1.170    21.50      0.0262    8.77   

       Orientation  EulerNumber  BoundingBox1  BoundingBox2  ...  Co

In [4]:
import numpy as np
import sklearn 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,outputs,train_size=0.8)
print(x_train)
print(x_test)
print(y_train)
print(y_test)
import sklearn 
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=13)
model.fit(x_train,y_train)

       Solidity  Eccentricity  EquivDiameter  Extrema  FilledArea  Extent  \
1953       9.19         18.40          0.449   15.400     0.00431    5.01   
13292     12.10         22.80          0.585    6.950     0.00723    6.57   
13540     12.30         22.90          0.927   12.300     0.01720    2.35   
16638     14.10         21.90          4.960   12.500     0.46600   10.20   
1849      12.40         14.90          3.940    0.806     0.34900    9.21   
...         ...           ...            ...      ...         ...     ...   
7154       9.74         17.20          4.810   17.200     0.78700    7.47   
15275      4.48         18.10          3.320    7.940     0.21400    2.40   
16660     15.20          9.39          3.990   21.700     0.30100   12.10   
3174      10.60         20.10          2.860   10.200     0.16300    8.00   
15795     12.20         13.50          4.150    2.470     0.44500    8.72   

       Orientation  EulerNumber  BoundingBox1  BoundingBox2  ...  ConvexHul

KNeighborsClassifier(n_neighbors=13)

In [6]:
y_pred=model.predict(x_test)
print(y_pred)
print(y_test)

['Yeast' 'Spirogyra' 'Raizopus' ... 'Volvox' 'Aspergillus sp' 'Diatom']
10734             Yeast
18922         Spirogyra
1183           Raizopus
19708          Raizopus
232            Protozoa
              ...      
19090          Ulothrix
13121          Raizopus
16267            Volvox
5832     Aspergillus sp
16622            Diatom
Name: microorganisms, Length: 4274, dtype: object


In [9]:
import sklearn 
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[302  28  23  11  38  29   4  63  36  17]
 [  5 139   6   4  14   0   1  44  29  15]
 [ 26   2  65   3  12   4   0  13   8   4]
 [ 18  16   4  91   5   3   2  31   8   9]
 [  7   0   0   0 563   1   0   0   0   6]
 [  6   0   0   0   0 323   0   0   0   0]
 [  0   3   1   0   5   1  60  13   2   7]
 [ 42  31  13  14  57   9   6 777  74  30]
 [ 13  21   9   0  29   0   7  36 441  28]
 [  7  18   0   3  35   0   1  55  35 353]]
